### ISSUE TITLE
Singleuser base image hsmodels dep out of date

### ISSUE THREAD

**Issue by aaraney** [CUAHSI/jupyterhub#1]
## Summary

Dave Tarboton reported an issue when trying to download [this](https://hydroshare.org/resource/ce0f48aff42142b3a12147e8c5113dac) HydroShare resource using [hydroshare on jupyter](https://github.com/hydroshare/hydroshare_on_jupyter) from CUAHSI's JupyterHub. Ive include the trace back from the logs below (I scrubbed some information for privacy purposes).

## Issue

Having looked into the issue, I was not able to reproduce the bug with a fresh install of [`hsclient`](https://github.com/hydroshare/hsclient) (v0.2.1), the library hydroshare on jupyter uses to interact with hydroshare. After more digging, I found the version of [`hsmodels`](https://github.com/hydroshare/hsmodels), the package that provides schema definitions for hydroshare resources (`hsclient` is dependent on `hsmodels`), installed in the singleuser image in production is out of date and a new version of `hsmodels` has been released to resolve the issue Dave found. Currently, the singleuser image has version `0.4.3` of `hsmodels` installed. The most recent release is `0.4.6`. 

Hydroshare on jupyter trace back
```shell
AttributeError: 'NoneType' object has no attribute 'get'
      File "pydantic/main.py", line 1001, in pydantic.main.validate_model
File "pydantic/main.py", line 329, in pydantic.main.BaseModel.__init__
File "pydantic/main.py", line 676, in pydantic.main.BaseModel.validate
File "pydantic/class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
File "pydantic/fields.py", line 1118, in pydantic.fields.ModelField._apply_validators
File "pydantic/fields.py", line 1071, in pydantic.fields.ModelField._validate_singleton
File "pydantic/fields.py", line 854, in pydantic.fields.ModelField.validate
File "pydantic/fields.py", line 1064, in pydantic.fields.ModelField._validate_singleton
File "pydantic/fields.py", line 898, in pydantic.fields.ModelField._validate_sequence_like
File "pydantic/fields.py", line 865, in pydantic.fields.ModelField.validate
File "pydantic/main.py", line 1022, in pydantic.main.validate_model
File "pydantic/main.py", line 329, in pydantic.main.BaseModel.__init__
return user_schemas[schema](**rdf_metadata.dict())
File "/opt/conda/lib/python3.9/site-packages/hsmodels/schemas/__init__.py", line 73, in load_rdf
instance = load_rdf(file_str)
File "/opt/conda/lib/python3.9/site-packages/hsclient/hydroshare.py", line 179, in _retrieve_and_parse
self._retrieved_metadata = self._retrieve_and_parse(self.metadata_path)
File "/opt/conda/lib/python3.9/site-packages/hsclient/hydroshare.py", line 124, in _metadata
return self._metadata
File "/opt/conda/lib/python3.9/site-packages/hsclient/hydroshare.py", line 216, in metadata
res.metadata
File "/opt/conda/lib/python3.9/site-packages/hsclient/hydroshare.py", line 1010, in resource
resource = session.resource(resource_id)
File "/opt/conda/lib/python3.9/site-packages/hydroshare_on_jupyter/server.py", line 403, in get
result = method(*self.path_args, **self.path_kwargs)
File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
Traceback (most recent call last):
HTTPServerRequest(protocol='https', host='jupyterhub.cuahsi.org', method='GET', uri='/user/dtarb/syncApi/resources/ce0f48aff42142b3a12147e8c5113dac/download', version='HTTP/1.1', remote_ip='')
Uncaught exception GET /user/dtarb/syncApi/resources/ce0f48aff42142b3a12147e8c5113dac/download
```

## Actionable

To resolve this issue, we just need to rebuild the singleuser base image and pull in the latest release of `hsmodels`. Having looked at the singleuser base image we are currently using, no changes to the Dockerfile should be required. @Castronova can you update this ticket once the image has been rebuilt and pushed to production?

**Comment by aaraney** [comment]
https://github.com/CUAHSI/cuahsi-stacks/issues/26 fixes this issue. See that issue for added context.
