### ISSUE TITLE
Terminal Fails to Load in Tree View

### ISSUE THREAD

**Issue by Castronova** [CUAHSI/jupyterhub#4]
From David Tarboton:

> This issue is reproducible using this resource https://www.hydroshare.org/resource/ce0f48aff42142b3a12147e8c5113dac/, but I think occurs with any resource.
>
> 1. From resource, Open With CUAHSI JupyterHub
> 2. Sign in with HydroShare
> 3. Authorize
> 4. Select Python – v3.8 server option
>
> I get to tree view
> https://jupyterhub.cuahsi.org/user/demo/tree/downloads/ce0f48aff42142b3a12147e8c5113dac/ce0f48aff42142b3a12147e8c5113dac/data/contents
> I can open notebooks and use them.
>
> However if I select New Terminal from the menu below I get 503: Service Unavailable
>
> ![image002](https://user-images.githubusercontent.com/4822372/161607512-77845ed0-2ed5-4e57-a96c-439d8fd15f6b.png)

**Comment by Castronova** [comment]
This is the stack trace when I try to start a new terminal in `tree` view

``` python
[I 2022-04-04 18:25:05.222 SingleUserLabApp management:365] New terminal with automatic name: 4
[I 2022-04-04 18:25:05.224 SingleUserLabApp log:189] 200 POST /user/tonycastronova/api/terminals (tonycastronova@10.128.0.101) 641.05ms
[E 2022-04-04 18:25:05.561 SingleUserLabApp http1connection:67] Uncaught exception
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/tornado/http1connection.py", line 273, in _read_message
        delegate.finish()
      File "/opt/conda/lib/python3.9/site-packages/tornado/httpserver.py", line 387, in finish
        self.delegate.finish()
      File "/opt/conda/lib/python3.9/site-packages/tornado/routing.py", line 268, in finish
        self.delegate.finish()
      File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 2290, in finish
        self.execute()
      File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 2309, in execute
        self.handler = self.handler_class(
      File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 233, in __init__
        self.initialize(**kwargs)  # type: ignore
    TypeError: initialize() missing 1 required positional argument: 'name'
```

**Comment by Castronova** [comment]
It appears that this is a known issue (Dec 2021) when running the classic `tree` view ([see here](https://discourse.jupyter.org/t/nbclassic-terminal-throws-error/12224)). Looks like something that can be resolved by updating JupyterHub.

PR that resolves the issue is [here](https://github.com/jupyterlab/nbclassic/pull/79)
